# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Colin Brust"                                # Your name
  description: ""   # A brief slogan (optional)
  image: img/my_image.jpg
  
  favicon: img/favicon.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/favicon.png
    
    # your sub-pages
    left:
      # - text: "Projects"
      #   href: projects/index.qmd
      - text: "Research"
        href: research/index.qmd
      # - text: "Posts"
      #   href: posts/index.qmd
      - text: "Resume"
        href: cv/index.qmd
    
    # your social media handles
    right:
      - icon: github
        href: https://github.com/colinbrust/
      - icon: linkedin
        href: https://www.linkedin.com/in/colin-brust/
      # - icon: envelope
      #   aria-label: email
      #   href: "mailto:colin.brust@gmail.com"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2023 Marvin Schmitt CC BY-SA 4.0</span>
    right: |
      <span class="faux-block"><a href="https://github.com/marvinschmitt/quarto-website-template/">View template source on GitHub</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true